name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:$GITHUB_SHA .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:$GITHUB_SHA

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-react-app \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
